name: Generate DBC

on:
  push:
    # branches: [ main ]
  workflow_dispatch:  # allows manual trigger
  pull_request:

jobs:
  build-dbc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DBC generation script
        run: |
          python3 dbc_builder/main.py

      - name: Upload generated DBC (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: generated-dbc
          path: dbc/